[platform]
display_name = Bluesky
name = bluesky
; proto_id: 0 = OAuth2, 1 = PNBA
proto_id = 0
; cat_id: 0 = Email, 1 = Message, 2 = Text, 3 = Bridge
cat_id = 2
; true or false
supports_offline_first = false
icon_svg = https://raw.githubusercontent.com/smswithoutborders/bluesky-oauth2-adapter/main/icons/bluesky.svg
icon_png = https://raw.githubusercontent.com/smswithoutborders/bluesky-oauth2-adapter/main/icons/bluesky.png

[author]
name = Promise Fru
email = info@promisefru.com
